export const MEMBERS = "MEMBERS"
export const LOADMOREMEMBERS = "LOADMOREMEMBERS"
export const UPDATE_MEMBER_INFORMATION = "UPDATE_MEMBER_INFORMATION"
// POST ACTIONS
export const POSTS = "POSTS"
export const UPDATE_POST = "UPDATE_POST"