export const MEMBERS = "MEMBERS"
export const LOADMOREMEMBERS = "LOADMOREMEMBERS"
export const UPDATE_MEMBER_INFORMATION = "UPDATE_MEMBER_INFORMATION"
export const DELETE_GDI_MEMBER = "DELETE_GDI_MEMBER"
export const ADD_GDI_MEMBER = "ADD_GDI_MEMBER"
// POST ACTIONS
export const POSTS = "POSTS"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"
export const ADD_POST = "ADD_POST"
export const LOAD_MORE_POSTS = "LOAD_MORE_POSTS"
export const GET_COMMENT = "GET_COMMENT"
export const LOAD_MORE_COMMENTS = "LOAD_MORE_COMMENTS"
export const DELETE_COMMENT = "DELETE_COMMENT"
// EVENT ACTIONS
export const EVENTS = "EVENTS"
export const UPDATE_EVENT = "UPDATE_EVENT"
export const DELETE_EVENT = "DELETE_EVENT"
export const ADD_EVENT = "ADD_EVENT"
export const LOAD_MORE_EVENTS = "LOAD_MORE_EVENTS"
// AUTH ACTIONS
export const LOG_OUT = "LOG_OUT"
export const LOGIN_USER = "LOGIN_USER"
// ADMIN ACTIONS
export const ADMIN_USERS = "ADMIN_USERS"
export const ADD_ADMIN = "ADD_ADMIN"
export const DELETE_ADMIN = "DELETE_ADMIN"
export const BLOCK_ADMIN = "BLOCK_ADMIN"
export const UNBLOCK_ADMIN = "UNBLOCK_ADMIN"
export const EDIT_ADMIN = "EDIT_ADMIN"

// NEWSLETTER ACTIONS
export const MAIL_TEMPLATES = "MAIL_TEMPLATES"
export const NEWSLETTER_THEME = "NEWSLETTER_THEME"
export const SITE_SUBSCRIBERS = "SITE_SUBSCRIBERS"
export const LOAD_MORE_SUBSCRIBERS = "LOAD_MORE_SUBSCRIBERS"
export const DELETE_SUBSCRIBER = "DELETE_SUBSCRIBER"

// GALLERY ACTION
export const GALLERY_PHOTOS = "GALLERY_PHOTOS"
export const DELETE_PHOTO_FILE = "DELETE_PHOTO_FILE"
export const UPLOADED_FILES = "UPLOADED_FILES"
export const LOAD_MORE_PHOTOS = "LOAD_MORE_PHOTOS"